const items = [
  {
    name: "POCO X6 Pro - Yellow",
    description: "POCO X6 Pro - Yellow back | 8GB RAM | 256GB Storage",
    price: 80,
    currency: "€",
    image: "images/poco.jpg",
    storeUrl: "https://www.hind.ee/p/poco-x6-pro/",
    storeName: "hind.ee",
  },
  {
    name: "Robot Vacuum Cleaner",
    description: "Xiaomi Robot Vacuum S20+ | Mopping and Vacuuming | Efficient Cleaning",
    price: 90,
    currency: "€",
    image: "images/cleaner.JPG",
    storeUrl: "https://www.mi.com/global/product/xiaomi-robot-vacuum-s20-plus/specs/",
    storeName: "mi.com",
  },
  {
    name: "Stationary Bicycle",
    description: "Tunturi Cardio Fit E30 Ergometer | Sturdy Construction | Easy to move | Comfortable Seat",
    price: 90,
    currency: "€",
    image: "images/bike.JPG",
    storeUrl: "https://sportlik.ee/velotrenazoeoer-tunturi-cardio-fit-e30-ergometer-1",
    storeName: "sportlik.ee",
  },
  {
    name: "Monitor LG UltraWide 34''",
    description: "Monitor LG UltraWide 34'' IPS Full HD 2560x1080 75Hz 5ms (GtG) HDR10 HDMI AMD FreeSync Dynamic Action Sync 34WP550-B",
    price: 90,
    currency: "€",
    image: "images/uw-monitor.JPG",
    storeUrl: "https://www.lg.com/br/monitores/monitores-ultrawide/34wp550-b/",
    storeName: "lg.com",
  },
  {
    name: "Black Table",
    description: "Black table | 108x60cm | Modern design | Sturdy construction",
    price: 40,
    currency: "€",
    image: "images/table.JPG",
    storeUrl: "https://www.amazon.de/-/en/Lenovo-Y27h-30-Response-DisplayPort-FreeSync/dp/B0BCQHS87X",
    storeName: "amazon.de",
    reserved: true,
  },
  {
    name: "PlayStation 5 + 3 Controllers",
    description: "PlayStation 5 Digital Edition Console | 825GB SSD | 4K Gaming | 3 DualSense Wireless Controller",
    price: 320,
    currency: "€",
    image: "images/ps5.JPG",
    storeUrl: "https://www.amazon.de/-/en/PlayStation-CFI-1216B-Playstation-Digital-Konsole/dp/B08H98GVK8/",
    storeName: "amazon.de",
    reserved: true,
  },
  {
    name: "Pink Gaming Chair",
    description: "Cougar Armor Elite Eva Pink Gaming Chair CGR-ELI-PNB. Used, but in good condition. No issues, works perfectly.",
    price: 50,
    currency: "€",
    image: "images/pink-chair.JPG",
    storeUrl: "https://arvutitark.ee/en/home-and-beauty/manguritoolid-ja-lauad/manguritoolid/cougar-gaming-chair-armor-elite-eva-pink-cgr-eli-pnb-1317885",
    storeName: "arvutitark.ee",
  },
  {
    name: "Black Table",
    description: "Black Table 130x70cm | Modern Design | Sturdy Construction | Spacious Surface | Adjustable Height",
    price: 60,
    currency: "€",
    image: "images/big-table.JPG",
    storeUrl: "https://www.jysk.ee/lundtoft-ohusurvel-reguleeritava-korgusega-laud-131931-ee.html?___store=ee_et",
    storeName: "jysk.ee",
  },
  {
    name: "Black Table",
    description: "Black Table 100x60cm | Modern Design | Sturdy Construction | Spacious Surface",
    price: 30,
    currency: "€",
    image: "images/table2.JPG",
    storeUrl: "https://arvutitark.ee/en/home-and-beauty/manguritoolid-ja-lauad/mangurilauad/gaming-desk-huzaro-hero-18-black-1240124",
    storeName: "arvutitark.ee",
  },
  {
    name: "PC Gamer",
    description: "Ryzen 5 3600 | 16GB RAM | RTX 2060 | 1Tb SSD M.2",
    price: 250,
    currency: "€",
    image: "images/pc.JPG",
    storeUrl: "",
    storeName: "N/A",
    reserved: true,
  },
  {
    name: "Lenovo Monitor 27''",
    description: "Lenovo C27-35 Monitor | 27 Inch Full HD Monitor | 1920 x 1080 | 60Hz | Anti-Glare",
    price: 50,
    currency: "€",
    image: "images/monitor2.JPG",
    storeUrl: "https://www.amazon.de/-/en/Lenovo-Monitor-Response-FreeSync-Anti-Glare/dp/B0BT7RW85Y",
    storeName: "amazon.de",
    reserved: true,
  },
  {
    name: "Gaming Monitor Legion 27''",
    description: "Lenovo Legion | 27 Inch QHD Gaming Monitor | 2560 x 1440 | 180Hz | USB 3.2 | USB-C | HDMI | DisplayPort | AMD FreeSync | Speaker",
    price: 90,
    currency: "€",
    image: "images/gamer-monitor.JPG",
    storeUrl: "https://www.amazon.de/-/en/Lenovo-Y27h-30-Response-DisplayPort-FreeSync/dp/B0BCQHS87X",
    storeName: "amazon.de",
    reserved: true,
  },
  {
    name: "Black Chair Legend",
    description: "Black Chair Legend | Ergonomic Design | Adjustable Height | Comfortable Seating",
    price: 40,
    currency: "€",
    image: "images/black-chair.JPG",
    storeUrl: "https://www.jysk.ee/hallum-manguritool-jalatoega-126625-ee.html",
    storeName: "jysk.ee",
    reserved: true,
  },
  {
    name: "Black Drawer Unit",
    description: "Black drawer unit | Modern Design | Metal",
    price: 20,
    currency: "€",
    image: "images/drawer.jpg",
    storeUrl: "https://www.jysk.ee/klintholm-sahtliplokk-131929-ee.html",
    storeName: "jysk.ee",
    reserved: true,
  },
  {
    name: "Logitech G923 Gaming TRUE FORCE Racing Wheel",
    description: "Racing wheel with pedals for PS5, PS4 & PC. Used, but in great condition. Works perfectly. Comes with original box and all accessories.",
    price: 120,
    currency: "€",
    image: "images/wheel.JPG",
    storeUrl: "https://www.amazon.de/-/en/Logitech-feedback-response-leather-steering/dp/B07W7KFFFF?th=1",
    storeName: "amazon.de",
    reserved: true,
  },
];
